export {default as Category} from './category/Category'
export {default as Products} from './menu/Products'
export {default as AddProduct} from './menu/AddProduct'
export {default as users} from './users/Users'
export {default as Home} from './home/Home'
export {default as Dashboard} from './dashboard/Dashboard'
export {default as PageNotFound} from './home/PageNotFound'