export const ADD_TO_ADDRES = 'ADD_TO_ADDRES';
export const ADD_TO_ADDRES_REQUEST = 'ADD_TO_ADDRES_REQUEST';
export const ADD_TO_ADDRES_FAILED = 'ADD_TO_ADDRES_FAILED';

export const GET_ADDRES_REQUEST = 'GET_ADDRES_REQUEST';
export const GET_ADDRES_SUCCEED = 'GET_ADDRES_SUCCEED';
export const GET_ADDRES_FAILED = 'GET_ADDRES_FAILED';

export const FIND_ADDRES_REQUEST = 'FIND_ADDRES_REQUEST';
export const FIND_ADDRES_SUCCEED = 'FIND_ADDRES_SUCCEED';
export const FIND_ADDRES_FAILED = 'FIND_ADDRES_FAILED';

export const UPDATE_ADDRES_REQUEST = 'UPDATE_ADDRES_REQUEST';
export const UPDATE_ADDRES_SUCCEED = 'UPDATE_ADDRES_SUCCEED';

export const DELETE_ADDRES_REQUEST = 'DELETE_ADDRES_REQUEST';
export const DELETE_ADDRES_SUCCEED = 'DELETE_ADDRES_SUCCEED';