export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';

export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCEED = 'GET_CART_SUCCEED';
export const GET_CART_FAILED = 'GET_CART_FAILED';

export const FIND_CART_REQUEST = 'FIND_CART_REQUEST';
export const FIND_CART_SUCCEED = 'FIND_CART_SUCCEED';
export const FIND_CART_FAILED = 'FIND_CART_FAILED';

export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST';
export const UPDATE_CART_SUCCEED = 'UPDATE_CART_SUCCEED';

export const DELETE_CART_REQUEST = 'DELETE_CART_REQUEST';
export const DELETE_CART_SUCCEED = 'DELETE_CART_SUCCEED';