export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST';
export const ADD_ORDER_SUCCEED = 'ADD_ORDER_SUCCEED';
export const ADD_ORDER_FAILED = 'ADD_ORDER_FAILED';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCEED = 'GET_ORDER_SUCCEED';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';

export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST';
export const CANCEL_ORDER_SUCCEED = 'CANCEL_ORDER_SUCCEED';
export const CANCEL_ORDER_FAILED = 'CANCEL_ORDER_FAILED';


