export const GET_RECA_REQUEST = 'GET_RECA_REQUEST';
export const GET_RECA_SUCCEED = 'GET_RECA_SUCCEED';
export const GET_RECA_FAILED = 'GET_RECA_FAILED';

export const SET_CURRENT_RECA = 'SET_CURRENT_RECA';

export const CREATE_RECA_REQUEST = 'CREATE_RECA_REQUEST';
export const CREATE_RECA_SUCCEEDED = 'CREATE_RECA_SUCCEEDED';

export const FIND_RECA = 'FIND_RECA';

export const UPDATE_RECA_REQUEST = 'UPDATE_RECA_REQUEST';
export const UPDATE_RECA_SUCCEEDED = 'UPDATE_RECA_SUCCEEDED';

export const DELETE_RECA_REQUEST = 'DELETE_RECA_REQUEST';
export const DELETE_RECA_SUCCEEDED = 'DELETE_RECA_SUCCEEDED';

