export const GET_REME_REQUEST = 'GET_REME_REQUEST';
export const GET_REME_SUCCEED = 'GET_REME_SUCCEED';
export const GET_REME_FAILED = 'GET_REME_FAILED';

export const ADD_REME_REQUEST = 'ADD_REME_REQUEST'
export const ADD_REME_SUCCEED = 'ADD_REME_SUCCEED'
export const ADD_REME_FAILED = 'ADD_REME_FAILED';

export const SEARCH_REME_REQUEST = 'SEARCH_REME_REQUEST';
export const SEARCH_REME_SUCCEED = 'SEARCH_REME_SUCCEED';

export const CREATE_REME_REQUEST = 'CREATE_REME_REQUEST';
export const CREATE_REME_SUCCEEDED = 'CREATE_REME_SUCCEEDED';

export const FIND_REME_REQUEST = 'FIND_REME_REQUEST';
export const FIND_REME_SUCCEED = 'FIND_REME_SUCCED';

export const UPDATE_REME_REQUEST = 'UPDATE_REME_REQUEST';
export const UPDATE_REME_SUCCEEDED = 'UPDATE_REME_SUCCEEDED';

export const DELETE_REME_REQUEST = 'DELETE_REME_REQUEST';
export const DELETE_REME_SUCCEEDED = 'DELETE_REME_SUCCEEDED';