export const GET_RETO_REQUEST = 'GET_RETO_REQUEST';
export const GET_RETO_SUCCEED = 'GET_RETO_SUCCEED';
export const GET_RETO_FAILED = 'GET_RETO_FAILED';

export const ADD_RETO_REQUEST = 'ADD_RETO_REQUEST'
export const ADD_RETO_SUCCEED = 'ADD_RETO_SUCCEED'
export const ADD_RETO_FAILED = 'ADD_RETO_FAILED';

export const FIND_RETO_REQUEST = 'FIND_RETO_REQUEST';
export const FIND_RETO_SUCCEED = 'FIND_RETO_SUCCEED';

export const UPDATE_RETO_REQUEST = 'UPDATE_RETO_REQUEST';
export const UPDATE_RETO_SUCCEED = 'UPDATE_RETO_SUCCEED';

export const DELETE_RETO_REQUEST = 'DELETE_RETO_REQUEST';
export const DELETE_RETO_SUCCEED = 'DELETE_RETO_SUCCEED';